name: release-drafter
on:
concurrency:
  group: .github/workflows/release-drafter.yml-${{ github.ref }}
  cancel-in-progress: true
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
